### ISSUE TITLE
Error: Error: Cannot find module '/Users/jagadeeshchandrasekaran/wdio/webdriverio/file:/Users/jagadeeshchandrasekaran/wdio/webdriverio/src/web/tests/prereq/prerequisite.spec.ts'

### ISSUE THREAD

**Issue by JagadeeshC78** [JagadeeshC78/wdio#1]
webdriverio % npm run test-PREMACGCSYSAD

> webdriveriomochaframework@1.0.0 test-PREMACGCSYSAD
> npm run pretest && npm run remove-allure-results-folder && ENV=PreRequisite_SysAd_Mac_Eng_GC wdio src/wdio.conf.ts

> webdriveriomochaframework@1.0.0 pretest
> node killPort.mjs

> webdriveriomochaframework@1.0.0 remove-allure-results-folder
> node delAllure.mjs

Directory deleted
ENV variable: PreRequisite_SysAd_Mac_Eng_GC
Environment: {
  url: '',
  credential: { userName: '[]', password: '[]' },
  browser: 'Chrome',
  objectiveType: 'PreReq',
  os: 'Mac',
  userRole: 'SYSAD',
  language: 'English'
}
Browser: Chrome
Feature Type : PreReq
Specs to run: [ './web/tests/prereq/prerequisite.spec.ts' ]

Execution of 1 workers started at 2024-10-31T08:24:31.685Z

2024-10-31T08:24:31.695Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-10-31T08:24:31.696Z INFO @wdio/utils: Setting up browser driver for: chrome@stable
2024-10-31T08:24:31.697Z INFO @wdio/utils: Setting up browser binaries for: chrome@stable
2024-10-31T08:24:31.994Z INFO webdriver: Using Chromedriver v130.0.6723.92 from cache directory /var/folders/1g/ww2r7bgd0qd0qsggy8f8gp000000gn/T
2024-10-31T08:24:31.996Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-10-31T08:24:31.996Z INFO @wdio/local-runner: Start worker 0-0 with arg: src/wdio.conf.ts
2024-10-31T08:24:31.999Z DEBUG @wdio/local-runner: Send command run to worker with cid "0-0"
[0-0] 2024-10-31T08:24:32.738Z INFO @wdio/local-runner: Run worker command: run
[0-0] ENV variable: PreRequisite_SysAd_Mac_Eng_GC
[0-0] Environment: {
[0-0]   url: '',
[0-0]   credential: { userName: '[]', password: '[]' },
[0-0]   browser: 'Chrome',
[0-0]   objectiveType: 'PreReq',
[0-0]   os: 'Mac',
[0-0]   userRole: 'SYSAD',
[0-0]   language: 'English'
[0-0] }
[0-0] Browser: Chrome
[0-0] Feature Type : PreReq
[0-0] Specs to run: [ './web/tests/prereq/prerequisite.spec.ts' ]
[0-0] 2024-10-31T08:24:32.762Z DEBUG @wdio/runner: init remote session
_**[0-0] 2024-10-31T08:24:32.887Z WARN @wdio/mocha-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
[0-0] `browser` object has only `capabilities` and some flags like `isMobile`.
[0-0] Helper files that use other `browser` commands have to be moved to `before` hook.
[0-0] Spec file(s): file:///Users/jagadeeshchandrasekaran/wdio/webdriverio/src/web/tests/prereq/prerequisite.spec.ts
[0-0] Error: Error: Cannot find module '/Users/jagadeeshchandrasekaran/wdio/webdriverio/file:/Users/jagadeeshchandrasekaran/wdio/webdriverio/src/web/tests/prereq/prerequisite.spec.ts'**_
[0-0] Require stack:
[0-0] - /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/mocha/lib/nodejs/esm-utils.js
[0-0] - /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/mocha/lib/mocha.js
[0-0] - /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/mocha/index.js
[0-0] - /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/@wdio/mocha-framework/build/index.js
[0-0]     at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
[0-0]     at m._resolveFilename (file:///Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-RyGUjI6j.mjs:1:789)
[0-0]     at nextResolveSimple (/Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-DCnOAxY2.cjs:3:942)
[0-0]     at /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:2550
[0-0]     at /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1624
[0-0]     at resolveTsPaths (/Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-DCnOAxY2.cjs:3:760)
[0-0]     at Function.<anonymous> (/Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-DCnOAxY2.cjs:3:1038)
[0-0]     at Function.Module._resolveFilename (/Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsconfig-paths/src/register.ts:115:36)
[0-0]     at Module._load (node:internal/modules/cjs/loader:985:27)
[0-0]     at Module.require (node:internal/modules/cjs/loader:1235:19)
[0-0] RUNNING in chrome - file:///src/web/tests/prereq/prerequisite.spec.ts
[0-0] 2024-10-31T08:24:32.925Z DEBUG @wdio/runner: init remote session
[0-0] 2024-10-31T08:24:32.926Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2024-10-31T08:24:32.971Z INFO webdriver: Using Chromedriver v130.0.6723.92 from cache directory /var/folders/1g/ww2r7bgd0qd0qsggy8f8gp000000gn/T
[0-0] 2024-10-31T08:24:32.998Z INFO chromedriver: Starting ChromeDriver 130.0.6723.92 (ef4f16c57010eb3e047ef101019b869296173bd9-refs/branch-heads/6723@{#1518}) on port 54282
[0-0] 2024-10-31T08:24:32.998Z INFO chromedriver: Remote connections are allowed by an allowlist (0.0.0.0).
[0-0] 2024-10-31T08:24:32.998Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[0-0] 2024-10-31T08:24:33.018Z INFO chromedriver: ChromeDriver was started successfully on port 54282.
[0-0] 2024-10-31T08:24:33.987Z INFO @wdio/utils: Started Chromedriver v130.0.6723.92 with params --port=54282 --allowed-origins=* --allowed-ips=0.0.0.0 in 1061ms on port 54282
[0-0] 2024-10-31T08:24:34.001Z INFO webdriver: [POST] http://localhost:54282/session
[0-0] 2024-10-31T08:24:34.001Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       acceptInsecureCerts: true,
[0-0]       'goog:chromeOptions': [Object],
[0-0]       webSocketUrl: true,
[0-0]       unhandledPromptBehavior: 'ignore'
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   }
[0-0] }
[0-0] 2024-10-31T08:24:34.015Z WARN chromedriver: [1730363074.015][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[0-0] 2024-10-31T08:24:34.015Z WARN chromedriver: [1730363074.015][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[0-0] 2024-10-31T08:24:35.471Z INFO webdriver: Register BiDi handler for session with id e4af5e5a0ea574a184730707767a1ca6
[0-0] 2024-10-31T08:24:35.471Z INFO webdriver: Connect to webSocketUrl ws://127.0.0.1:54282/session/e4af5e5a0ea574a184730707767a1ca6
[0-0] 2024-10-31T08:24:35.480Z INFO webdriver: Connected session to Bidi protocol
[0-0] 2024-10-31T08:24:35.481Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2024-10-31T08:24:35.482Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["log.entryAdded","browsingContext.navigationStarted"]}
[0-0] 2024-10-31T08:24:35.485Z INFO webdriver: BIDI COMMAND script.addPreloadScript { functionDeclaration: <PreloadScript[1267 bytes]>, contexts: undefined }
[0-0] 2024-10-31T08:24:35.486Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.navigationStarted","network.responseCompleted","network.beforeRequestSent","network.fetchError"]}
[0-0] 2024-10-31T08:24:35.486Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.userPromptOpened"]}
[0-0] 2024-10-31T08:24:35.487Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2024-10-31T08:24:35.487Z INFO webdriver: Connected to WebDriver Bidi interface at ws://127.0.0.1:54282/session/e4af5e5a0ea574a184730707767a1ca6
[0-0] 2024-10-31T08:24:35.487Z INFO webdriver: [GET] http://localhost:54282/session/e4af5e5a0ea574a184730707767a1ca6/window
[0-0] 2024-10-31T08:24:35.488Z INFO webdriver: [GET] http://localhost:54282/session/e4af5e5a0ea574a184730707767a1ca6/window
[0-0] 2024-10-31T08:24:35.490Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2024-10-31T08:24:35.490Z INFO webdriver: [GET] http://localhost:54282/session/e4af5e5a0ea574a184730707767a1ca6/window
[0-0] 2024-10-31T08:24:35.499Z INFO webdriver: RESULT 8C513A68FE72D26FAF0F2CD77A324464
[0-0] 2024-10-31T08:24:35.500Z INFO webdriver: BIDI COMMAND script.callFunction {"functionDeclaration":"<Function[220 bytes]>","awaitPromise":true,"arguments":[{"type":"string","value":"var __defProp = Object.defineProperty;var __name = function (target, value) { return __defProp(target, 'name', { value: value, configurable: true }); };var __globalThis = (typeof globalThis === 'object' && globalThis) || (typeof window === 'object' && window);__globalThis.__name = __name;"}],"target":{"context":"8C513A68FE72D26FAF0F2CD77A324464"}}
[0-0] 2024-10-31T08:24:35.503Z INFO webdriver: RESULT 8C513A68FE72D26FAF0F2CD77A324464
[0-0] 2024-10-31T08:24:35.505Z INFO webdriver: RESULT 8C513A68FE72D26FAF0F2CD77A324464
[0-0] 2024-10-31T08:24:35.506Z INFO webdriver: BIDI COMMAND script.addPreloadScript { functionDeclaration: <PreloadScript[482 bytes]>, contexts: ["8C513A68FE72D26FAF0F2CD77A324464"] }
[0-0] 2024-10-31T08:24:35.508Z DEBUG webdriver: BIDI RESULT {"id":1,"result":{},"type":"success"}
[0-0] 2024-10-31T08:24:35.511Z DEBUG webdriver: BIDI RESULT {"id":2,"result":{"script":"80d54ff4-2e7d-4bed-81f8-c936a9362728"},"type":"success"}
[0-0] 2024-10-31T08:24:35.513Z DEBUG webdriver: BIDI RESULT {"id":3,"result":{},"type":"success"}
[0-0] 2024-10-31T08:24:35.513Z DEBUG webdriver: BIDI RESULT {"id":4,"result":{},"type":"success"}
[0-0] 2024-10-31T08:24:35.517Z DEBUG webdriver: BIDI RESULT {"id":5,"result":{"realm":"-7889169737602250796.5829318623225050413","result":{"type":"undefined"},"type":"success"},"type":"success"}
[0-0] 2024-10-31T08:24:35.517Z DEBUG webdriver: BIDI RESULT {"id":6,"result":{"script":"9342b70e-3390-4e68-9d4e-ff88836999bc"},"type":"success"}
[0-0] 2024-10-31T08:24:35.517Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["script.message"]}
[0-0] 2024-10-31T08:24:35.518Z DEBUG webdriver: BIDI RESULT {"id":7,"result":{},"type":"success"}
[0-0] 2024-10-31T08:24:35.519Z INFO webdriverio:PolyfillManager: polyfill script added
[0-0] 2024-10-31T08:24:35.521Z DEBUG @wdio/utils:shim: Finished to run "after" hook in 0ms
[0-0] 2024-10-31T08:24:35.521Z ERROR @wdio/runner: Error: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
[0-0] `browser` object has only `capabilities` and some flags like `isMobile`.
[0-0] Helper files that use other `browser` commands have to be moved to `before` hook.
[0-0] Spec file(s): file:///Users/jagadeeshchandrasekaran/wdio/webdriverio/src/web/tests/prereq/prerequisite.spec.ts
[0-0] Error: Error: Cannot find module '/Users/jagadeeshchandrasekaran/wdio/webdriverio/file:/Users/jagadeeshchandrasekaran/wdio/webdriverio/src/web/tests/prereq/prerequisite.spec.ts'
[0-0] Require stack:
[0-0] - /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/mocha/lib/nodejs/esm-utils.js
[0-0] - /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/mocha/lib/mocha.js
[0-0] - /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/mocha/index.js
[0-0] - /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/@wdio/mocha-framework/build/index.js
[0-0]     at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
[0-0]     at m._resolveFilename (file:///Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-RyGUjI6j.mjs:1:789)
[0-0]     at nextResolveSimple (/Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-DCnOAxY2.cjs:3:942)
[0-0]     at /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:2550
[0-0]     at /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1624
[0-0]     at resolveTsPaths (/Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-DCnOAxY2.cjs:3:760)
[0-0]     at Function.<anonymous> (/Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-DCnOAxY2.cjs:3:1038)
[0-0]     at Function.Module._resolveFilename (/Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsconfig-paths/src/register.ts:115:36)
[0-0]     at Module._load (node:internal/modules/cjs/loader:985:27)
[0-0]     at Module.require (node:internal/modules/cjs/loader:1235:19)
[0-0]     at MochaAdapter._loadFiles (/Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/@wdio/mocha-framework/build/index.js:86:35)
[0-0]     at async MochaAdapter.init (/Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/@wdio/mocha-framework/build/index.js:55:9)
[0-0]     at async adapterFactory.init (/Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/@wdio/mocha-framework/build/index.js:319:22)
[0-0]     at async Runner.run (file:///Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/@wdio/runner/build/index.js:657:23)
[0-0]  Error:  Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): file:///Users/jagadeeshchandrasekaran/wdio/webdriverio/src/web/tests/prereq/prerequisite.spec.ts
Error: Error: Cannot find module '/Users/jagadeeshchandrasekaran/wdio/webdriverio/file:/Users/jagadeeshchandrasekaran/wdio/webdriverio/src/web/tests/prereq/prerequisite.spec.ts'
Require stack:
- /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/mocha/lib/nodejs/esm-utils.js
- /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/mocha/lib/mocha.js
- /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/mocha/index.js
- /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/@wdio/mocha-framework/build/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at m._resolveFilename (file:///Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-RyGUjI6j.mjs:1:789)
    at nextResolveSimple (/Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-DCnOAxY2.cjs:3:942)
    at /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:2550
    at /Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1624
    at resolveTsPaths (/Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-DCnOAxY2.cjs:3:760)
    at Function.<anonymous> (/Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsx/dist/register-DCnOAxY2.cjs:3:1038)
    at Function.Module._resolveFilename (/Users/jagadeeshchandrasekaran/wdio/webdriverio/node_modules/tsconfig-paths/src/register.ts:115:36)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
[0-0] 2024-10-31T08:24:35.522Z INFO webdriver: COMMAND deleteSession()
[0-0] 2024-10-31T08:24:35.522Z INFO webdriver: [DELETE] http://localhost:54282/session/e4af5e5a0ea574a184730707767a1ca6
[0-0] 2024-10-31T08:24:35.581Z INFO webdriver: RESULT null
[0-0] 2024-10-31T08:24:35.582Z INFO webdriver: Kill driver process with PID 81225
2024-10-31T08:24:35.702Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - file:///src/web/tests/prereq/prerequisite.spec.ts
2024-10-31T08:24:35.703Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-10-31T08:24:35.703Z INFO @wdio/cli:launcher: Run onComplete hook
Report successfully generated to allure-report
0
serve
serve
Allure report successfully generated
^C

Ended WebDriver sessions gracefully after a SIGINT signal was received!
2024-10-31T08:24:38.763Z INFO @wdio/local-runner: Shutting down spawned worker

webdriverio % 2024-10-31T08:24:39.015Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2024-10-31T08:24:39.015Z INFO @wdio/local-runner: shutting down

**Comment by JagadeeshC78** [comment]
Additional info, just in case, it matters
webdriverio % npm list
webdriveriomochaframework@1.0.0 /Users/jagadeeshchandrasekaran/wdio/webdriverio
├── @babel/register@7.25.9
├── @types/jest@29.5.14
├── @types/jquery@3.5.32
├── @types/mocha@10.0.9
├── @types/user-home@2.0.2
├── @wdio/allure-reporter@8.40.6
├── @wdio/cli@9.2.4
├── @wdio/globals@9.2.4
├── @wdio/local-runner@9.2.4
├── @wdio/mocha-framework@7.33.0
├── @wdio/runner@9.2.4
├── @wdio/spec-reporter@8.40.6
├── @wdio/types@8.40.6
├── allure-commandline@2.31.0
├── child_process@1.0.2
├── chromedriver@130.0.1
├── dotenv@16.4.5
├── exceljs@4.4.0
├── expect-webdriverio@5.0.3
├── fs-extra@11.2.0
├── glob@11.0.0
├── ip@2.0.1
├── kill-port@2.0.1
├── list-files-in-dir@0.1.5
├── lru-cache@11.0.1
├── minimatch@9.0.5
├── mocha@10.7.3
├── mochawesome-report-generator@6.2.0
├── nodemailer@6.9.16
├── open@9.1.0
├── pdf-merger-js@4.3.1
├── ps-node@0.1.6
├── puppeteer@22.15.0
├── rimraf@6.0.1
├── rxjs@7.8.1
├── selenium-standalone@9.5.0
├── selenium-webdriver@4.25.0
├── shell-quote@1.8.1
├── ts-node@10.9.2
├── tsconfig-paths@4.2.0
├── typescript@4.9.5
├── user-home@3.0.0
├── uuid@10.0.0
├── wdio-mochawesome-reporter@2.0.1
├── webdriverio@9.2.4
└── webextension-polyfill@0.10.0
